Resources:
  GenoVicCloudFrontDistribution:
    Type: 'AWS::CloudFront::Distribution'
    Properties:
      DistributionConfig:
        Enabled: true
        Origins:
        - DomainName: !ImportValue genovic-gos-devdaniel-ApiGatewayDnsName
          Id: testalb
          CustomOriginConfig:
            HTTPSPort: 443
            OriginProtocolPolicy: https-only
        DefaultCacheBehavior: 
          AllowedMethods: 
            - GET
            - HEAD
          CachedMethods: 
            - GET
            - HEAD
          MinTTL: 100
          DefaultTTL: 100
          MaxTTL: 300
          ForwardedValues:
             QueryString: true
          TargetOriginId: testalb
          ViewerProtocolPolicy: allow-all