
Resources:
#cloudfront code  
  GenoVicCloudFrontDistribution:
    Type: 'AWS::CloudFront::Distribution'
    Properties:
      DistributionConfig:
        Enabled: true
        Origins:
        - DomainName: http://my-alb-755320302.us-east-1.elb.amazonaws.com/
          Id: my-alb
          OriginPath: /
          CustomOriginConfig:
            HTTPPort: 80
            OriginProtocolPolicy: http-only
        DefaultCacheBehavior: 
          AllowedMethods: 
            - GET
            - HEAD
            - OPTIONS
            - PUT
          CachedMethods: 
            - GET
            - HEAD
          MaxTTL: 300
          TargetOriginId: my-alb
          ViewerProtocolPolicy: allow-all
        WebACLId: !Ref GenoVicWaf
  #WAF Code      
  GenoVicWaf:
    Type: 'AWS::WAFv2::WebACL'
    Properties:
      Name: GenoVic-waf
      Scope: CLOUDFRONT
      DefaultAction:
          Block: {}
      VisibilityConfig:
        CloudWatchMetricsEnabled: true
        MetricName: genovic-waf-metric
        SampledRequestsEnabled: true
      Rules:
      - Name: AWSManagedRulesCommonRuleSet
        Statement:
          ManagedRuleGroupStatement: 
           VendorName: AWS
           Name: CommonRuleSet    
        Priority: 1
        Action:
          Block: {}
        OverrideAction:
          Count: {}
        VisibilityConfig:
          SampledRequestsEnabled: true
          CloudWatchMetricsEnabled: true
          MetricName: CommonRuleSetMetric    
      - Name: AWSManagedRulesSQLiRuleSet
        Statement:
         ManagedRuleGroupStatement:
           VendorName: AWS
           Name: SQLiRuleSet
        Priority: 2
        Action:
          Block: {}
        OverrideAction:
          Count: {}
        VisibilityConfig:
          SampledRequestsEnabled: true
          CloudWatchMetricsEnabled: true
          MetricName: SQLiMteric
      - Name: AWSManagedRulesKnownBadInputs
        Statement:
          ManagedRuleGroupStatement:
            Name: BadInputSet
            VendorName: AWS
        Priority: 3
        Action:
          Block: {}
        OverrideAction:
          Count: {}
        VisibilityConfig:
          SampledRequestsEnabled: true
          CloudWatchMetricsEnabled: true
          MetricName: BadInputMetric
      - Name: AWSManagedRulesATPRuleSet
        Statement:
          ManagedRuleGroupStatement:
            Name: ATPRuleSet
            VendorName: AWS
        Priority: 4
        Action:
          Block: {}
        OverrideAction:
          Count: {}
        VisibilityConfig:
          SampledRequestsEnabled: true
          CloudWatchMetricsEnabled: true
          MetricName: ATPRuleSetMetric
      - Name: AWSManagedRulesIPReputationList
        Priority: 5
        Statement:
          ManagedRuleGroupStatement:
            Name: IPReputationListSet
            VendorName: AWS
        Action:
          Block: {}
        OverrideAction:
          Count: {}
        VisibilityConfig:
          SampledRequestsEnabled: true
          CloudWatchMetricsEnabled: true
          MetricName: IPReputationListMetric
      - Name: AWSManagedRulesBotControlRuleSet
        Priority: 6
        Statement:
          ManagedRuleGroupStatement:
            Name: BotControlSet
            VendorName: AWS
        Action:
          Block: {}
        OverrideAction:
          Count: {}
        VisibilityConfig:
          SampledRequestsEnabled: true
          CloudWatchMetricsEnabled: true
          MetricName: BotContolSetMetric
      
    
  